### ISSUE TITLE
How much user this system can handle

### ISSUE THREAD

**Issue by alimaqsood3** [mojtaba-motevali/Media-server#1]
Hi can you please tell me How many users this system can handle? in single room and how many Rooms we can create

**Comment by mojtaba-motevali** [comment]
Hello alimaqsood3. This system can handle ~ 500 consumers in each worker thread and each room can spawn more worker threads when needed ( vertically scaled )  so it depends on your server's hardware statistics.  As for numbers rooms, software doesn't limit you to a certain number of rooms so no limitations here.
